### ISSUE TITLE
Refine the log system for the deployment

### ISSUE THREAD

**Issue by iskey** [huaweicloud/xpanse#185]
Refine the log system for the deployment, so we can bring the executing logs out when an error occurs.

**Comment by swaroopar** [comment]
@iskey I would suggest to stream all logs only to stdout with all information possible. Later it can be streamed out to any logging tools and the queries can be built on top of it. Writing to different files must be avoided.
Same is also mentioned in the 12 factor app - https://12factor.net/logs

**Comment by iskey** [comment]
Yes, I think you are right.
